FROM ruby:2.2-slim
RUN apt-get update -qq && apt-get install -y build-essential libmysqlclient-dev
RUN mkdir /pipeline-api
WORKDIR /pipeline-api
ADD Gemfile /pipeline-api/Gemfile
ADD Gemfile.lock /pipeline-api/Gemfile.lock
RUN bundle install
ADD . /pipeline-api
