angular.module 'servicio', ['angularModalService',
                            'toggle-switch',
                            'ui.bootstrap',
                            'ui.router',
                            'ngAria',
                            'ngTouch',
                            'ngLodash',
                            'ngCookies',
                            'ngAnimate',
                            'ngSanitize',
                            'ngMessages',
                            'ngResource',
                            'toastr',
                            'rails',
                            'naif.base64']
