
production:
  GMAIL_USERNAME: ''
  GMAIL_PASSWORD: ''
  JWT_SECRET: ''
  BASE_URL: ''

staging:
  GMAIL_USERNAME: ''
  GMAIL_PASSWORD: ''
  JWT_SECRET: ''
  BASE_URL: ''

development:
  GMAIL_USERNAME: 'ns.pipeline.tester@gmail.com'
  GMAIL_PASSWORD: 'ONEPERSONATHOUSANDFEELINGS'
  JWT_SECRET: ''

  BASE_URL: 'http://localhost:9000/#/'
