
production:
  GMAIL_USERNAME: ''
  GMAIL_PASSWORD: ''
  GOOGLE_KEY: ''
  GOOGLE_SECRET: ''
  JWT_SECRET: ''
  BASE_URL: ''

staging:
  GMAIL_USERNAME: ''
  GMAIL_PASSWORD: ''
  GOOGLE_KEY: ''
  GOOGLE_SECRET: ''
  JWT_SECRET: ''
  BASE_URL: ''

development:
  GMAIL_USERNAME: ''
  GMAIL_PASSWORD: ''
  GOOGLE_KEY: ''
  GOOGLE_SECRET: ''
  JWT_SECRET: ''

  BASE_URL: 'http://localhost:9000/#/'
