version: '2'

services:
  web:
   build: .
   command: bash -c "chmod +x wait-for-it/wait-for-it.sh && wait-for-it/wait-for-it.sh db:3306 && rake db:create && rake db:migrate && rake db:reset && && RAILS_ENV=development puma"
   depends_on:
     - db
   ports:
     - "80:9292"
   links:
     - db
   volumes:
     - .:/api
  worker:
    image: api_web
    command: bash -c "wait-for-it/wait-for-it.sh db:3306 && rake jobs:work"
  db:
   image: mysql:latest
   ports:
     - "3306:3306"
   environment:
     MYSQL_DATABASE: db
     MYSQL_ROOT_PASSWORD: root
   volumes:
     - ./docker-entrpoint-initdb.d:/docker-entrypoint-initdb.d
