source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.4'
gem 'rails-api'

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring', :group => :development

#For debugging purposes
gem 'pry-rails', '~> 0.3.4'
gem 'pry', '~> 0.10.1'

#MYSQL adapter
gem 'mysql2', '~> 0.3.20'

#Puma server
gem 'puma'

# Rails smell
gem "rails_best_practices"

#Delayed Jobs
gem 'delayed_job_active_record'

#Daemons for delayed_job
gem "daemons"

#Active model serializer
gem 'active_model_serializers', '~> 0.10.0'

#User authentication
#gem 'authlogic', '~> 3.4.6'
gem 'jwt'
gem 'httpclient'

#Using interactors to store business logic
gem 'interactor', '~> 3.1.0'
gem 'interactor-rails', '~> 2.0.1'

gem 'rails-erd', '~> 1.4.2'

gem 'will_paginate', '~> 3.0.5'

# To use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'

gem 'figaro'
# To use Jbuilder templates for JSON
# gem 'jbuilder'


group :development, :test do
  gem "rspec-rails"
  gem 'factory_girl_rails'
  gem 'database_cleaner', :require => false
end
# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
